server:
  port: 8080
  servlet:
    context-path: /leaguestanding

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,httptrace
  trace:
    http:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      getStandings:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 80
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      getStandings:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 10s
  ratelimiter:
    instances:
      getStandings:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s

apifootball:
  base:
    url: https://apiv3.apifootball.com
  apiKey: 9bb66184e0c8145384fd2cc0f7b914ada57b4e8fd2e4d6d586adcc27c257a978

spring:
  jackson:
    default-property-inclusion: non_null

app:
  name: league standing application
  api:
    title: Get League Standing API
    version: 1.0.0
    description: description
    base-package: com.api.football.leaguestanding
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    swagger:
      enable: true